---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: cs-server
  ports:
  -  name: http
     protocol: TCP
     port: 9007
     targetPort: 9090
  type: LoadBalancer