apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
     containers:
     - name: mysql
       image: mysql/mysql-server
       ports:
       - containerPort: 3306
       command: ["/bin/sh", "-c", "mkdir /mnt/data"]
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: "test"
       - name: MYSQL_REPLICATION_USER
         value: 'demo'
       - name: MYSQL_REPLICATION_PASSWORD
         value: 'demo'

       volumeMounts: 
       - mountPath: /var/lib/mysql
         subPath: mysql
         name: data
       - mountPath: /etc/mysql/conf.d
         name: configmap
     volumes:
     - name: data
       persistentVolumeClaim: 
         claimName: mysql-pvc   
     - name: configmap
       configMap:
         name: mysql   
