apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    server-id=1
    log-bin=black-bin.log
    innodb_flush_log_at_trx_commit=1
    sync_binlog=1
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    server-id=2
    relay-log-index=slave-relay-bin.index
    relay-log=slave-relay-bin
